# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: tour
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: Research & Equipment
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Open positions
    url: publication
    weight: 50
  - name: Gallery
    url: contact
    weight: 60
  - name: More
    url: contact
    weight: 70
